[flavor_groups.shader_packs]
name = "Shader Packs"
description = "Whether to download shaders or not and iris."
side = "both"

[[flavor_groups.shader_packs.choices]]
id = "enable"
name = "Enable"
description = "Yes i love it"

[[flavor_groups.shader_packs.choices]]
id = "disable"
name = "Disable"
description = "my potato of a pc cant handle it"

[metafile."/mods/iris-neoforge-1-8-14-beta-1-mc1-21-1.pw.toml"]
flavors = ["enable"]

[metafile."/shaderpacks/bsl-v10-1-3.pw.toml"]
flavors = ["enable"]

[metafile."/shaderpacks/complementaryreimagined-r5-8-1.pw.toml"]
flavors = ["enable"]

[metafile."/shaderpacks/complementaryunbound-r5-8-1.pw.toml"]
flavors = ["enable"]
